### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0

### ISSUE THREAD

**Issue by jkone27** [fsprojects/SQLProvider#808]
**Describe the bug**

The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not create the connection, most likely this means that the connectionString is wrong. See error from Npgsql to troubleshoot: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)F# Compiler[3033](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-messages/fs3033)

**To Reproduce**
.net8, updating an old project to use pgsql instead of mssql

**Expected behavior**
i would expect it to read the connection, but seems some internal dll library load issue

**Screenshots**
<img width="641" alt="image" src="https://github.com/fsprojects/SQLProvider/assets/10419217/e189e484-2b17-40e8-97f6-de66da9aac70">

**Desktop (please complete the following information):**
 - OS: macOs
 - .NET 8.0
 - vscode + ionide

**Comment by Thorium** [comment]
Is this duplicate of #807 ?

**Comment by jkone27** [comment]
seems like, 
i also have tried adding 
`Microsoft.Extensions.Logging.Abstractions' as extra #r nuget reference, but does not seem to fix/resolve

**Comment by Thorium** [comment]
This should help: https://github.com/fsprojects/SQLProvider/issues/807#issuecomment-1887829039

**Comment by jkone27** [comment]
do you suggest to add System.Text.Json ? 
i already have access to `Microsoft.Extensions.Logging.Abstractions` but does not seem to help, do we have a working PGSQL sample/integration test in the solution? maybe it can be added to avoid regressions?

**Comment by Thorium** [comment]
> do you suggest to add System.Text.Json ?

If you use the latest Postgres drivers, yes, you need that. Either to ResolutionPath or as direct reference to your project.

> do we have a working PGSQL sample/integration

The [comment](https://github.com/fsprojects/SQLProvider/issues/807#issuecomment-1887829039) had a working zip-file as example. That is not updated to the test-samples: All these DB drivers change so often that it's hard to keep the samples up-to-date. But I'm accepting PRs if anyone wants to update the samples in the solution.

> why support older targets?

It seems  most of the type-providers target .NET Standard 2.0 and .NET Standard 2.1. 
I'd expect that the main reason for that is that TypeProviders have to run also on design-time, so even when you target to new .NET, all the IDEs (like Visual Studio 2022) are not running on those, some are still using the .NET Standard 2.0. So they have to run on both runtimes.

Besides of that, SQLProvider is used by some enterprises (like US Navy, I've heard) and many large enterprises still use the legacy .NET Framework, which has Microsoft guaranteed support longer than any of the new existing .NET. So I'm not seeing to break the backward-compatibility any time soon.

**Comment by jkone27** [comment]
thanks, trying to update this branch nof an old project/showcase here, and got a bit stuck
https://github.com/jkone27/FsharpWebApi/blob/update-to-net8-and-pgsql/FSharp/Services/Types.fs

**Comment by jkone27** [comment]
is there ways to automate the creation of this folder somehow, copyng from the root nuget folder maybe? 

<img width="447" alt="image" src="https://github.com/fsprojects/SQLProvider/assets/10419217/ad890d4f-b69c-4f5e-97f5-baf31abe0601">

**Comment by jkone27** [comment]
still not working with above suggestions, i add the zip here if interested (based on linked script) / macos gives an error in `Microsoft.Bcl.AsyncInteractive 8.0.0 missing` 
[myTestV2.zip](https://github.com/fsprojects/SQLProvider/files/14470687/myTestV2.zip)

**Comment by jkone27** [comment]
tried this script, but i notice on MAC i cannot find that Microsoft.Bcl even after adding the library in my project? 
https://gist.github.com/jkone27/3752f33a7b365e98ec2fb45d63549e7a

only these libs are found
<img width="391" alt="image" src="https://github.com/fsprojects/SQLProvider/assets/10419217/10eff616-32c6-4fe3-b3fc-603ff30d002a">

```fsproj

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Npgsql" Version="8.0.1" />
    <PackageReference Include="SQLProvider" Version="1.3.23" />
    <PackageReference Include="System.Text.Json" Version="8.0.1" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
  </ItemGroup>
  ```

**Comment by Thorium** [comment]
The ReferencePath you probably need .NET Standard 2.0 version of the library and not the .NET8 version, because your VSCode is likely not running on .NET8 yet!  Don't worry, the ReferencePath is just for the IDE and compiler, it's not the executable runtime code. So if you target for the .NET8 then the .NET8 libraries should go to the bin-folder (as they go if they are project references).

**Comment by jkone27** [comment]
cannot make it work i tried copying only netstandard2.0 libs as well...

**Comment by Thorium** [comment]
I was testing your .fsx with my Mac and a few notes:

- I hate debugging Mac as with Windows VS2022 you can just attach VS2022 to another process of VS2022 (devenv.exe). And then you know what is missing or fails to load. I don't know how to attach a debugger on VS Code with Mac.

- VS Code seems not to refresh loaded dlls when reference paths are modified, so you need to sometimes restart VS Code for changes to take effect if you modify the ResolutionPath.

- To make debugging simpler, I added support for semicolon separated reference paths for latest SQLProvider (1.3.28). So instead of copying files manually you can just do something like this:
```sharp
    [<Literal>]
    let resPath = "~/.nuget/packages/npgsql/8.0.2/lib/netstandard2.0;~/.nuget/packages/system.text.json/8.0.0/lib/netstandard2.0;~/.nuget/packages/system.threading.channels/8.0.0/lib/netstandard2.0;~/.nuget/packages/microsoft.bcl.asyncinterfaces/8.0.0/lib/netstandard2.0;~/.nuget/packages/microsoft.extensions.logging.abstractions/8.0.0/lib/netstandard2.0;~/.nuget/packages/system.memory.data/8.0.0/lib/netstandard2.0;~/.nuget/packages/system.diagnostics.diagnosticsource/8.0.0/lib/netstandard2.0"
```

- But referencing files directly from NuGet cache has potential dis-advantage/side-effect that the referenced file might never be loaded with this computer before, and thus not be in the NuGet cache. So you must do also something like this (and execute it once) for system to load the packages:
```fsharp
#r "nuget:Npgsql"
#r "nuget:SQLProvider"
#r "nuget:System.Threading.Channels"
#r "nuget:Microsoft.Bcl.AsyncInterfaces"
#r "nuget:System.Memory.Data"
#r "nuget:Microsoft.Extensions.Logging.Abstractions"
#r "nuget:System.Text.Json"
#r "nuget:System.Diagnostics.DiagnosticSource"
```

**Comment by knocte** [comment]
> But referencing files directly from NuGet cache has potential dis-advantage/side-effect that the referenced file might never be loaded with this computer before, and thus not be in the NuGet cache. So you must do also

I was thinking if this is an alternative workaround: add the following entry in your Nuget.config and try to build your solution just once:
```
<add key="globalPackagesFolder" value="packages" />
```

(And of course use paths starting with `./packages/...` instead of `~/.nuget/packages/...`.) This looks less ugly than `#r` FSI script workaround, right?

**Comment by jkone27** [comment]
sorry if i havent replied earlier, i will follow up and test again, thanks for takng this time!

**Comment by knocte** [comment]
> much better if this package could all somehow work normally also for beginners is not very easy to use this package correctly

I'm all for that! Especially considering that because of this kind of issues with SqlProvider, my teammates have already been researching for alternatives. But IMO rewriting our data layer is a bigger effort than fixing the root cause of these issues in SqlProvider repo itself. Let's work together to iron this out.

> maybe is possible to do >multitarget builds/publish packages, and also build for NET8 with simplified dependencies?

Good question for Thorium, do we want a SqlProvider nuget package that targets more than one framework version?

**Comment by jkone27** [comment]
@Thorium still get error, the error mention connection but right below mention Microsoft.Logging.Abstractions ,in my case i have pgsql running locally from docker and connection works perfectly fine, so the problem is def not connection

would you mind trying run DOCKER desktop with PGSQL in it? 
also docker could be a nice way to test different db providers
https://hub.docker.com/_/postgres

<img width="994" alt="image" src="https://github.com/fsprojects/SQLProvider/assets/10419217/1ea5313d-2da3-44db-bb1c-d508e55d791b">

**Comment by Thorium** [comment]
>     [<Literal>]
>     let resPath = 
>         """
>         ~/.nuget/packages/npgsql/8.0.2/lib/netstandard2.0;
>         ~/.nuget/packages/system.text.json/8.0.0/lib/netstandard2.0;
>         ~/.nuget/packages/system.threading.channels/8.0.0/lib/netstandard2.0;
>         ~/.nuget/packages/microsoft.bcl.asyncinterfaces/8.0.0/lib/netstandard2.0;
>         ~/.nuget/packages/microsoft.extensions.logging.abstractions/8.0.0/lib/netstandard2.0;
>         ~/.nuget/packages/system.memory.data/8.0.0/lib/netstandard2.0;
>         ~/.nuget/packages/system.diagnostics.diagnosticsource/8.0.0/lib/netstandard2.0
>         """

Uhmm, there was no .Trim() of these paths when using `;`, added now in 1.3.31 version.
But I think the core-issue is that a reference is missing still, e.g. `microsoft.extensions.logging.abstractions` is having a dependency to `Microsoft.Extensions.DependencyInjection.Abstractions`, `System.Threading.Tasks.Extensions` and `System.Buffers`. We only need the dlls that are actually in use by the database driver npgsql itself, so if they add random dependencies-of-dependencies which are not in the execution path of the code, that should be ok.

**Comment by jkone27** [comment]
i added the missing dependencies, still does not load `Microsoft.Extension.Logging.Abstractions` for me

```
#r "nuget:Npgsql"
#r "nuget:SQLProvider"
#r "nuget:System.Threading.Channels"
#r "nuget:Microsoft.Bcl.AsyncInterfaces"
#r "nuget:System.Memory.Data"
#r "nuget:Microsoft.Extensions.Logging.Abstractions"
#r "nuget:System.Text.Json"
#r "nuget:System.Diagnostics.DiagnosticSource"
#r "nuget: Microsoft.Extensions.DependencyInjection.Abstractions"
#r "nuget: System.Buffers, 4.5.1"
#r "nuget: System.Memory, 4.5.5"

open System
open FSharp.Data.Sql
open Npgsql

[<AutoOpen>]
module Settings =

    [<Literal>]
    let resPath = 
        """
        ~/.nuget/packages/npgsql/8.0.2/lib/netstandard2.0;
        ~/.nuget/packages/system.text.json/8.0.0/lib/netstandard2.0;
        ~/.nuget/packages/system.threading.channels/8.0.0/lib/netstandard2.0;
        ~/.nuget/packages/microsoft.bcl.asyncinterfaces/8.0.0/lib/netstandard2.0;
        ~/.nuget/packages/microsoft.extensions.logging.abstractions/8.0.0/lib/netstandard2.0;
        ~/.nuget/packages/microsoft.extensions.dependencyinjection.abstractions/8.0.0/lib/netstandard2.0;
        ~/.nuget/packages/system.buffers/4.5.1/lib/netstandard2.0;
        ~/.nuget/packages/system.memory/4.5.1/lib/netstandard2.0;
        ~/.nuget/packages/system.memory.data/8.0.0/lib/netstandard2.0;
        ~/.nuget/packages/system.diagnostics.diagnosticsource/8.0.0/lib/netstandard2.0
        """

```

reloaded multiple times, error is still on logging abstractions, not dependency injection or buffer or memory deps:
<img width="603" alt="image" src="https://github.com/fsprojects/SQLProvider/assets/10419217/cb987266-4f5e-49de-a179-e8c9895db844">


https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/

> 
<img width="816" alt="image" src="https://github.com/fsprojects/SQLProvider/assets/10419217/6415606c-436a-4209-add6-da1b0828cebc">

is there a way to get this right, 
or to have the error be more meaninful and descriptive on what needs to be done to make the TP work?
maybe a more meaningful error pointing to the solution could be already a great help

Thank you so much for your help

**Comment by Thorium** [comment]
Yes I think we can improve the error message. I'll create SQLProvider 1.3.32 and hope that helps.

Btw your path has system.memory/4.5.1/ where it should be system.memory/4.5.5/

**Comment by knocte** [comment]
> Yes I think we can improve the error message. I'll create SQLProvider 1.3.32 and hope that helps.
> Btw your path has system.memory/4.5.1/ where it should be system.memory/4.5.5/

@jkone27 were you able to test/fix both things above?

**Comment by jkone27** [comment]
will check again as last time wasnt able to fix actually, thanks a lot for taking this time! but no i wasn't able to fix yet : /

**Comment by Thorium** [comment]
I just released 1.3.36 containing another similar kind of small fix for some other database, but it's common code. so it could help here too.

**Comment by FraMecca** [comment]
I am having the same problem with .NET 8 and Intellij Rider

**Comment by dlidstrom** [comment]
I used to have this issue. Today I tried again to upgrade from Npgsql 6 to 9 and got it working. Here's my pre-build script:

```pwsh
$ErrorActionPreference = "Stop"

$packagesAndPaths=@(
  @{
    name = "System.Runtime.CompilerServices.Unsafe"
    path = "6.0.0/lib/netstandard2.0"
  }
  @{
    name = "Microsoft.Extensions.Logging.Abstractions"
    path = "8.0.2/lib/net8.0"
  }
)

$nugetPath=(dotnet nuget locals global-packages --list).Split(' ')[1]
New-Item -ItemType Directory -Name lib -Force

foreach ($item in $packagesAndPaths) {
  $nugetDll = "$($item.name).dll"
  $fullPath = "$nugetPath$($item.name.ToLower())/$($item.path)/$nugetDll"
  Copy-Item $fullPath ./lib
  " $fullPath > Copied $nugetDll into lib for type provider."
}
```

and my project file has this:

```xml
  <Target Name="TypeProvidersSetup" BeforeTargets="BeforeCompile">
    <Exec Command="pwsh ./prebuild.ps1" />
  </Target>
```

and, finally, my context is setup like so:

```fsharp
type DatabaseProvider =
  SqlDataProvider<
    DbVendor,
    ConnString,
    "",
    "lib", // the folder where dll's are copied into
    IndivAmount,
    NullableColumnType.OPTION,
    owner>
```

**Comment by jkone27** [comment]
fixed with latest version (net8)  for macos

```fsharp
#r "nuget: SQLProvider"
#r "nuget: Npgsql"
open FSharp.Data.Sql
open System

module DB = 

    // uses F# SQLProvider with PGSQL connection string for docker compose
    // https://fsprojects.github.io/SQLProvider/core/postgresql.html
    let [<Literal>] dbVendor = Common.DatabaseProviderTypes.POSTGRESQL
    let [<Literal>] connString = "Host=localhost;Port=5432;Username=user;Password=password;Database=mydb"

    // the resolution path needs to be aware of #r nuget and the fact that this is a "temp F# project" created by executing an .fsx script
    // [Loading /Users/admin/.packagemanagement/nuget/Projects/78008--86fcbb22-7111-4bc7-82d3-2771e40a54f2/Project.fsproj.fsx]
    // module FSI_0003.Project.fsproj

    let [<Literal>] resPath = "~/.nuget/packages/Npgsql/9.0.2/lib/net8.0/Npgsql.dll" // THIS WORKED FOR ME
    let [<Literal>] indivAmount = 1000
    let [<Literal>] useOptTypes = Common.NullableColumnType.OPTION
    let [<Literal>] owner = "public" // or "dbo" for MSSQL

    type sql =
        SqlDataProvider<
            dbVendor,
            connString,
            "", 
            resPath,
            indivAmount,
            useOptTypes,
            owner>

    let ctx = sql.GetDataContext()
```

**Comment by toburger** [comment]
This works for me only in parts. It works in an F# Script and in Visual Studio Code everything seems fine.

But when I use it inside a F# project like so:

```fsharp
module Db

open FSharp.Data.Sql


let [<Literal>] dbVendor = Common.DatabaseProviderTypes.POSTGRESQL
let [<Literal>] connString = "User ID=username;Host=localhost;Database=dbname"

// the resolution path needs to be aware of #r nuget and the fact that this is a "temp F# project" created by executing an .fsx script
// [Loading /Users/admin/.packagemanagement/nuget/Projects/78008--86fcbb22-7111-4bc7-82d3-2771e40a54f2/Project.fsproj.fsx]
// module FSI_0003.Project.fsproj

let [<Literal>] resPath = "~/.nuget/packages/Npgsql/9.0.2/lib/net8.0/Npgsql.dll" // THIS WORKED FOR ME
let [<Literal>] indivAmount = 1000
let [<Literal>] useOptTypes = Common.NullableColumnType.OPTION
let [<Literal>] owner = "public" // or "dbo" for MSSQL

type sql =
    SqlDataProvider<
        dbVendor,
        connString,
        "", 
        resPath,
        indivAmount,
        useOptTypes,
        owner>

let ctx = sql.GetDataContext()
```

and try to compile the project the error is back:

```sh
% dotnet build
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/tobias/Desktop/test/Db.fs(19,5): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not create the connection, most likely this means that the connectionString is wrong. See error from Npgsql to troubleshoot: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified., Path: /Users/tobias/Desktop/test/~/.nuget/packages/Npgsql/9.0.2/lib/net8.0/Npgsql.dllCurrent execution platform: .NETCoreApp,Version=v8.0 Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. [/Users/tobias/Desktop/test/test.fsproj]
/Users/tobias/Desktop/test/Db.fs(19,5): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not create the connection, most likely this means that the connectionString is wrong. See error from Npgsql to troubleshoot: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified., Path: /Users/tobias/Desktop/test/~/.nuget/packages/Npgsql/9.0.2/lib/net8.0/Npgsql.dllCurrent execution platform: .NETCoreApp,Version=v8.0 Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. [/Users/tobias/Desktop/test/test.fsproj]
/Users/tobias/Desktop/test/Db.fs(28,15): error FS0039: The type 'Object' does not define the field, constructor or member 'GetDataContext'. [/Users/tobias/Desktop/test/test.fsproj]
```

------

Visual Studio Code works fine:

![Image](https://github.com/user-attachments/assets/ec18c17b-8cae-4793-ad04-b86abe1925a2)

**Comment by dlidstrom** [comment]
@toburger in the compiler error message you can see that the compiler has not expanded ~ to your home folder.

```
Path: /Users/tobias/Desktop/test/~/.nuget/packages/Npgsql/9.0.2/lib/net8.0/Npgsql.dll
``` 

I think you must use an absolute path.

**Comment by toburger** [comment]
Thanks for the advice, but using the absolute path (for me /Users/tobias/.nuget/packages/Npgsql/9.0.2/lib/net8.0/Npgsql.dll) didn't work neither. Now the error message becomes:

```sh
/Users/tobias/Desktop/test/Db.fs(18,5): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not create the connection, most likely this means that the connectionString is wrong. See error from Npgsql to troubleshoot: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified., Path: /Users/tobias/.nuget/packages/Npgsql/9.0.2/lib/net8.0/Npgsql.dllCurrent execution platform: .NETCoreApp,Version=v8.0 Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. [/Users/tobias/Desktop/test/test.fsproj]
/Users/tobias/Desktop/test/Db.fs(18,5): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not create the connection, most likely this means that the connectionString is wrong. See error from Npgsql to troubleshoot: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified., Path: /Users/tobias/.nuget/packages/Npgsql/9.0.2/lib/net8.0/Npgsql.dllCurrent execution platform: .NETCoreApp,Version=v8.0 Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. [/Users/tobias/Desktop/test/test.fsproj]
/Users/tobias/Desktop/test/Db.fs(27,15): error FS0039: The type 'Object' does not define the field, constructor or member 'GetDataContext'. [/Users/tobias/Desktop/test/test.fsproj]
```

Double checking:

![Image](https://github.com/user-attachments/assets/7e02e9d7-a376-4eed-ae37-5956d647e0bb)

**Comment by Thorium** [comment]
The "reference assemblies path" are compile-time, not runtime.
If you run IDE made with .NET Framework (like Visual Studio 2022), then you can't reference Net 8 dll but you have to reference .NET Standard 2.0 dll (or .NET framework dll). If you run IDE that is made with .NET 8, or refers F# via .NET 8 compiler, then fine.
At runtime you are probably running your assembly on .NET 8 so runtime you can use .NET 8 dlls.

**Comment by toburger** [comment]
So do I understand you correctly: messing with the ResolutionPath only applies to the "design time" part of the Type Provider and does not affect the compilation?
How do I fix the compilation part then?

**Comment by toburger** [comment]
Thanks you for the clarification.

I feel stupid, this solutions works for me: https://github.com/fsprojects/SQLProvider/issues/808#issuecomment-2663232726

**Comment by Thorium** [comment]
Hi, could you test this package: https://www.nuget.org/packages/SQLProvider.PostgreSql/1.5.0-alpha3
I'm trying to split SQL-provider into multiple packages within one database, and load it via direct dependencies, so there wouldn't be a need for resolutionPath at all.

**Comment by Thorium** [comment]
> Hi, could you test this package

It is used by:
1) Changing the NuGet package from SQLProvider to SQLProvider.Postgresql 
2) Changing the FSharp.Data.Sql.TypeProviderConnection to FSharp.Data.Sql.Postgresql.TypeProviderConnection 

Everything else should work as before.

**Comment by webwarrior-ws** [comment]
@Thorium 
I tested the new package.
Here are my findings:
1. I could not replace `SQLProvider` with `SQLProvider.Postgresql`, both have to be present.
2. I deleted `lib` folder and removed `ResolutionPath` parameter, and it worked on my Windows machine.
3. However, on Linux (GithubCI) I got build errors like this:
```
Error: /home/runner/work/travelbuds/travelbuds/src/DBLayer/PostgreSQLTripsRepository.fs(19,5): error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Could not create the connection, most likely this means that the connectionString is wrong. See error from Npgsql to troubleshoot: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified., Path: /home/runner/work/travelbuds/travelbuds/src/DBLayerCurrent execution platform: .NETCoreApp,Version=v8.0 Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. [/home/runner/work/travelbuds/travelbuds/src/DBLayer/DBLayer.fsproj]
```

**Comment by Thorium** [comment]
@webwarrior-ws thanks for testing. Microsoft.Extensions.Logging.Abstractions is a dependency of Npgsql. I added a direct hard-coded dependency to Microsoft.Extensions.Logging.Abstractions to SQLProvider.PostgreSql 1.5.0-alpha4, hopefully that helps.

**Comment by webwarrior-ws** [comment]
> [@webwarrior-ws](https://github.com/webwarrior-ws) thanks for testing. Microsoft.Extensions.Logging.Abstractions is a dependency of Npgsql. I added a direct hard-coded dependency to Microsoft.Extensions.Logging.Abstractions to SQLProvider.PostgreSql 1.5.0-alpha4, hopefully that helps.

It didn't help. Got the same errors.

**Comment by Thorium** [comment]
Oh, sorry, there was a typo in deployment script. Can you try https://www.nuget.org/packages/SQLProvider.PostgreSql/1.5.0-alpha5 :-D

**Comment by webwarrior-ws** [comment]
> Can you try to remove the "SQLProvider" and only use "SQLProvider.Postgresql", is that fixed now?

No. If I remove `SQLProvider` package I get
```
error FS0039: The type 'SqlDataProvider' is not defined.
```

**Comment by Thorium** [comment]
even if you do `open FSharp.Data.Sql.Postgresql` ?

**Comment by webwarrior-ws** [comment]
> even if you do `open FSharp.Data.Sql.Postgresql` ?

Then I also get
```
error FS0039: The namespace 'Postgresql' is not defined.
```

**Comment by Thorium** [comment]
Thanks, fixed!

**Comment by webwarrior-ws** [comment]
@Thorium 
I tested new version of `SQLProvider.PostgreSql` (`1.5.0-alpha8`) and got the same errors.

**Comment by webwarrior-ws** [comment]
Class `FSharp.Data.Sql.PostgreSql.SqlDataProvider` that is referenced in the documentation doesn't exist. There is no namespace `FSharp.Data.Sql.PostgreSql`

**Comment by Thorium** [comment]
hi, the latest version is 1.5.0 (non-alpha). can you try with that please?

**Comment by webwarrior-ws** [comment]
> hi, the latest version is 1.5.0 (non-alpha). can you try with that please?

Tried. It works fine on Windows without `SQLProvider` package and using new `FSharp.Data.Sql.PostgreSql` namespace.

However, on Linux (GithubCI) I now get the following errors:
```
error FS3031 : The type provider '/home/runner/work/travelbuds/travelbuds/packages/sqlprovider.postgresql/1.5.0/lib/net8.0/FSharp.Data.SqlProvider.PostgreSql.dll' reported an error : Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.SqlProvider.Postgresql.DesignTime.dll' which cannot be loaded from path '/home/runner/work/travelbuds/travelbuds/packages/sqlprovider.postgresql/1.5.0/lib/net8.0/FSharp.Data.SqlProvider.Postgresql.DesignTime.dll'. The exception reported was: System.IO.FileNotFoundException - Could not load file or assembly '/home/runner/work/travelbuds/travelbuds/packages/sqlprovider.postgresql/1.5.0/lib/net8.0/FSharp.Data.SqlProvider.Postgresql.DesignTime.dll'. The system cannot find the file specified. [/home/runner/work/travelbuds/travelbuds/src/DBLayer/DBLayer.fsproj]
FSC : warning FS3005: Referenced assembly '/home/runner/work/travelbuds/travelbuds/packages/sqlprovider.postgresql/1.5.0/lib/net8.0/FSharp.Data.SqlProvider.PostgreSql.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found [/home/runner/work/travelbuds/travelbuds/src/DBLayer/DBLayer.fsproj]
```
